# Generated by Django 4.2.4 on 2023-09-08 14:30

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adhar_id', models.CharField(max_length=10, unique=True)),
                ('contact_number', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('land_number', models.AutoField(primary_key=True, serialize=False)),
                ('locality', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('active_from', models.DateField(auto_now_add=True)),
                ('active_till', models.DateField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_land_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandOwnershipRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.land')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandTypeTaxList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('TRANSPORT', 'Transport'), ('RECREATIONAL', 'Recreational'), ('INVESTMENT', 'Investment'), ('ECOSENSITIVE', 'Ecosensitive'), ('FOREST', 'Forest'), ('WET', 'Wet'), ('RANGE', 'Range'), ('BARREN', 'Barren')], max_length=20, unique=True)),
                ('land_tax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('tax_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('tax_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.land')),
                ('registry_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.landownershipregistry')),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoicePayment',
            fields=[
                ('tax_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payed_amount', models.IntegerField()),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('tax_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='LandGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('TRANSPORT', 'Transport'), ('RECREATIONAL', 'Recreational'), ('INVESTMENT', 'Investment'), ('ECOSENSITIVE', 'Ecosensitive'), ('FOREST', 'Forest'), ('WET', 'Wet'), ('RANGE', 'Range'), ('BARREN', 'Barren')], max_length=20)),
                ('location_coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('boundary_polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.FloatField()),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_geography', to='api.land')),
            ],
        ),
        migrations.CreateModel(
            name='GovbodyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('LOCAL', 'Local'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'A user with the same email already exists.'}, max_length=254, unique=True)),
                ('gov_body_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(blank=True, related_name='gov_body_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='gov_body_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gov_body_Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('locality', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(default='INDIA', max_length=20)),
                ('gov_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.govbodyuser')),
            ],
        ),
    ]
