# Generated by Django 4.2.4 on 2023-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandTypeTaxList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('TRANSPORT', 'Transport'), ('RECREATIONAL', 'Recreational'), ('INVESTMENT', 'Investment'), ('ECOSENSITIVE', 'Ecosensitive'), ('FOREST', 'Forest'), ('WET', 'Wet'), ('RANGE', 'Range'), ('BARREN', 'Barren')], max_length=20, unique=True)),
                ('land_tax', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='taxinvoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
