# Generated by Django 4.2.4 on 2023-08-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_gov_body_user_govbodyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='parent_land_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.land'),
        ),
    ]
