# Generated by Django 4.2.4 on 2023-09-05 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normaluser',
            name='district',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='GovBodyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('LOCAL', 'Local'), ('DISTRICT', 'District'), ('STATE', 'State')], max_length=20)),
                ('email', models.EmailField(error_messages={'unique': 'A user with the same email already exists.'}, max_length=254, unique=True)),
                ('gov_body_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=12)),
                ('groups', models.ManyToManyField(blank=True, related_name='gov_body_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='gov_body_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GovBodyAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('locality', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(default='INDIA', max_length=20)),
                ('gov_body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.govbodyuser')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.govbodyuser'),
        ),
        migrations.DeleteModel(
            name='Gov_body_user',
        ),
    ]
