# Generated by Django 4.2.4 on 2023-09-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_test',
            new_name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='replay_to',
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_set', to='api.comments'),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='blog_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reactions', to='api.blogs'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='api.blogs'),
        ),
        migrations.AlterField(
            model_name='votereaction',
            name='blog_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_reactions', to='api.blogs'),
        ),
    ]
