# Generated by Django 4.2.4 on 2023-08-17 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gov_body_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("DISTRICT", "District"),
                            ("STATE", "State"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("gov_body_name", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=12)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="Govuser_Profile_photos"
                    ),
                ),
                ("user_otp", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="gov_body_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="gov_body_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gov_body_wallet",
            fields=[
                ("wallet_id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.IntegerField(default=0)),
                (
                    "Gov_body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.gov_body_user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gov_body_wallet_transaction",
            fields=[
                (
                    "wallet_transaction_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "wallet_transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "Deposit"), ("WITHDRAWAL", "Withdrawal")],
                        max_length=50,
                    ),
                ),
                ("wallet_transaction_date", models.DateField(auto_now_add=True)),
                ("wallet_transaction_status", models.BooleanField(default=True)),
                ("wallet_transaction_amount", models.IntegerField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.gov_body_wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gov_body_Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("locality", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("country", models.CharField(default="INDIA", max_length=20)),
                (
                    "gov_body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.gov_body_user",
                    ),
                ),
            ],
        ),
    ]
