# Generated by Django 4.2.4 on 2023-08-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main_section_description',
            new_name='main_section_descriptions',
        ),
        migrations.AlterField(
            model_name='main_section_images',
            name='image',
            field=models.ImageField(upload_to='main_section_images'),
        ),
        migrations.AlterField(
            model_name='product_section',
            name='image',
            field=models.ImageField(upload_to='product_section'),
        ),
        migrations.AlterField(
            model_name='service_section',
            name='image',
            field=models.ImageField(upload_to='service_section'),
        ),
    ]
